export const FETCH_CAPTCHA = 'FETCH_CAPTCHA'
export const TRACK_PACKAGE = 'TRACK_PACKAGE'

export const CAPTCHA_TEXT_CHANGE = 'CAPTCHA_TEXT_CHANGE'
export const TRACKING_TEXT_CHANGE = 'TRACKING_TEXT_CHANGE'
export const PACKAGE_NAME_TEXT_CHANGE = 'PACKAGE_NAME_TEXT_CHANGE'

export const ADD_PACKAGE = 'ADD_PACKAGE'
export const REMOVE_PACKAGE = 'REMOVE_PACKAGE'
export const REMOVE_ALL_PACKAGES = 'REMOVE_ALL_PACKAGES'
export const LOAD_PACKAGES = 'LOAD_PACKAGES'
